CREATE DATABASE STORAGE_DLHI
USE STORAGE_DLHI

GO
CREATE TABLE SUPPILER (
	ID	UNIQUEIDENTIFIER NOT NULL,
	NAME_SUPPIER NVARCHAR(100),
	NAME_COMPANY_SUPPLIER NVARCHAR(MAX),
	ADDRESS_SUPPLIER NVARCHAR(MAX),
	PHONE CHAR(12),
	EMAIL NVARCHAR(MAX),
	NOTE NVARCHAR(MAX),

	CONSTRAINT PK_SUPPLIER PRIMARY KEY (ID),
)

GO
CREATE TABLE UNIT (
	ID UNIQUEIDENTIFIER NOT NULL,
	NAME_UNIT NVARCHAR(20),

	CONSTRAINT PK_UNIT PRIMARY KEY (ID),
)

GO
CREATE TABLE GROUP_CONSUMABLE (
	ID UNIQUEIDENTIFIER NOT NULL,
	NAME_GROUP_CONSUMABLE NVARCHAR(50),

	CONSTRAINT PK_GROUP_CONSUMABLE PRIMARY KEY (ID),
)

GO
CREATE TABLE TYPE_CONSUMABLE (
	ID UNIQUEIDENTIFIER NOT NULL,
	NAME_TYPE_CONSUMABLE NVARCHAR(100),

	CONSTRAINT PK_TYPE_CONSUMABLE PRIMARY KEY (ID),
)

GO
CREATE TABLE  CONSUMABLE (
	ID UNIQUEIDENTIFIER NOT NULL,
	CODE CHAR(100),
	NAME_CONSUMABLE NVARCHAR(100),
	PICTURE NVARCHAR(MAX),
	NOTE NVARCHAR(MAX),
	ENG_NAME_CONSUMABLE NVARCHAR(MAX),
	
	UNIT_ID UNIQUEIDENTIFIER,
	GROUP_CONSUMABLE_ID UNIQUEIDENTIFIER,
	TYPE_CONSUMABLE_ID UNIQUEIDENTIFIER,

	CONSTRAINT PK_CONSUMABLE PRIMARY KEY (ID),
	CONSTRAINT FK_COMSUMABLE_UNIT FOREIGN KEY (UNIT_ID) REFERENCES UNIT(ID),
	CONSTRAINT FK_COMSUMABLE_GROUP_CONSUMABLE FOREIGN KEY (GROUP_CONSUMABLE_ID) REFERENCES GROUP_CONSUMABLE(ID),
	CONSTRAINT FK_COMSUMABLE_TYPE_CONSUMABLE FOREIGN KEY (TYPE_CONSUMABLE_ID) REFERENCES TYPE_CONSUMABLE(ID),
)

----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
INSERT INTO SUPPILER 
VALUES (NEWID(), N'VƯƠNG BỬU', NULL, NULL)

INSERT INTO UNIT 
VALUES (NEWID(), N'PC')

INSERT INTO GROUP_CONSUMABLE 
VALUES (NEWID(), N'SP')

INSERT INTO TYPE_CONSUMABLE 
VALUES (NEWID(), N'DL-FCT')

INSERT INTO CONSUMABLE 
VALUES (NEWID(), 'DL-FCT0001', N'Xà beng', '', '', N'CROWBAR', 'fd1e547e-973b-4aa8-bd25-40cbb796e242', '71fddadd-3533-4db4-b4e3-e99100a0e643', '15927036-3704-40c6-9b3f-5ab5bf6055fd' )


