CREATE DATABASE STORAGE_DLHI
USE STORAGE_DLHI

GO
CREATE TABLE SUPPLIER (
	ID	UNIQUEIDENTIFIER NOT NULL,
	CODE NVARCHAR(50),
	NAME_SUPPIER NVARCHAR(100),
	NAME_COMPANY_SUPPLIER NVARCHAR(MAX),
	ADDRESS NVARCHAR(MAX),
	PHONE CHAR(12),
	EMAIL NVARCHAR(MAX),
	NOTE NVARCHAR(MAX),

	CONSTRAINT PK_SUPPLIER PRIMARY KEY (ID),
)

GO
CREATE TABLE SUPPLIER_TYPE (
	ID UNIQUEIDENTIFIER NOT NULL,
	NAME NVARCHAR(20),

	CONSTRAINT PK_SUPPLIER_TYPES PRIMARY KEY (ID),
)

GO
CREATE TABLE UNIT (
	ID UNIQUEIDENTIFIER NOT NULL,
	NAME NVARCHAR(20),

	CONSTRAINT PK_UNIT PRIMARY KEY (ID),
)

GO
CREATE TABLE GROUPS (
	ID UNIQUEIDENTIFIER NOT NULL,
	NAME NVARCHAR(50),

	CONSTRAINT PK_GROUP_CONSUMABLE PRIMARY KEY (ID),
)

GO
CREATE TABLE TYPES (
	ID UNIQUEIDENTIFIER NOT NULL,
	NAME NVARCHAR(100),

	CONSTRAINT PK_TYPE_CONSUMABLE PRIMARY KEY (ID),
)

GO 
CREATE TABLE ITEM (
	ID UNIQUEIDENTIFIER NOT NULL,
	CODE CHAR(100),
	NAME NVARCHAR(100),
	PICTURE NVARCHAR(MAX),
	NOTE NVARCHAR(MAX),
	ENG_NAME NVARCHAR(MAX),
	
	UNIT_ID UNIQUEIDENTIFIER,
	GROUP_ID UNIQUEIDENTIFIER,
	TYPE_ID UNIQUEIDENTIFIER,
	SUPPLIER_ID UNIQUEIDENTIFIER

	CONSTRAINT PK_CONSUMABLE PRIMARY KEY (ID),
	CONSTRAINT FK_COMSUMABLE_UNIT FOREIGN KEY (UNIT_ID) REFERENCES UNIT(ID),
	CONSTRAINT FK_COMSUMABLE_GROUP_CONSUMABLE FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(ID),
	CONSTRAINT FK_COMSUMABLE_TYPE_CONSUMABLE FOREIGN KEY (TYPE_ID) REFERENCES TYPES(ID),
	CONSTRAINT PK_ITEM_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(ID),
)

GO
CREATE TABLE  MPR (
	ID UNIQUEIDENTIFIER NOT NULL,
	CREATED DATETIME,
	EXPECTED_DELIVERY DATETIME,
	NOTE NVARCHAR(MAX),

	SUPPLIER_ID UNIQUEIDENTIFIER,

	CONSTRAINT PK_MPR PRIMARY KEY (ID),
	CONSTRAINT FK_MPR_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(ID),
)

GO
CREATE TABLE MPR_DETAIL (
	MPR_ID UNIQUEIDENTIFIER NOT NULL,
	ITEM_ID UNIQUEIDENTIFIER NOT NULL,
	MPR_NO NVARCHAR(100),
	USAGE NVARCHAR(MAX),
	QUANTITY INT,

	CONSTRAINT PK_MPR_DETAIL PRIMARY KEY (MPR_ID, ITEM_ID),
	CONSTRAINT FK_MPR_DETIAL_MPR FOREIGN KEY (MPR_ID) REFERENCES MPR(ID),
	CONSTRAINT FK_MPR_DETAIL_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID),
)

GO 
CREATE TABLE LOCATION_WAREHOUSE (
	ID UNIQUEIDENTIFIER NOT NULL,
	NAME NVARCHAR(MAX),

	CONSTRAINT PK_LOCATION_WAREHOUSE PRIMARY KEY (ID),
)

GO
CREATE TABLE PAYMENT_METHOD (
	ID UNIQUEIDENTIFIER NOT NULL,
	NAME NVARCHAR(MAX),

	CONSTRAINT PK_PAYMENT_METHOD PRIMARY KEY (ID),
)

GO
CREATE TABLE PO (
	ID UNIQUEIDENTIFIER NOT NULL,
	CREATED DATETIME,
	EXPECTED_DELIVERY DATETIME,
	TOTAL INT,

	SUPPLIER_ID UNIQUEIDENTIFIER,
	LOCATION_WAREHOUSE_ID UNIQUEIDENTIFIER,
	PAYMENT_METHOD_ID UNIQUEIDENTIFIER,

	CONSTRAINT PK_PO PRIMARY KEY (ID),
	CONSTRAINT FK_PO_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(ID),
	CONSTRAINT FK_PO_LOCATION_WAREHOUSE FOREIGN KEY (LOCATION_WAREHOUSE_ID) REFERENCES LOCATION_WAREHOUSE(ID),
	CONSTRAINT FK_PO_PAYMENT_METHOD FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENT_METHOD(ID),
)

GO 
CREATE TABLE PO_DETAIL (
	PO_ID UNIQUEIDENTIFIER NOT NULL,
	ITEM_ID UNIQUEIDENTIFIER NOT NULL,
	MPR_NO NVARCHAR(MAX),
	PO_NO NVARCHAR(MAX),
	PRICE INT,
	QUANTITY INT,

	CONSTRAINT PK_PO_DETAIL PRIMARY KEY (PO_ID, ITEM_ID),
	CONSTRAINT FK_PO_DETIAL_PO FOREIGN KEY (PO_ID) REFERENCES PO(ID),
	CONSTRAINT FK_PO_DETAIL_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID),
)

GO
CREATE TABLE IMPORT_ITEM (
	ID UNIQUEIDENTIFIER NOT NULL,
	CREATED DATETIME,
	BILL_NO NVARCHAR(MAX),
	QUANTITY INT,
	PRICE INT,
	TOTAL INT,

	SUPPLIER_ID UNIQUEIDENTIFIER,
	ITEM_ID UNIQUEIDENTIFIER,

	CONSTRAINT PK_IMPORT_ITEM PRIMARY KEY (ID),
	CONSTRAINT FK_IMPORT_ITEM_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(ID),
	CONSTRAINT FK_IMPORT_ITEM_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID),
)

GO
CREATE TABLE EXPORT_ITEM (
	ID UNIQUEIDENTIFIER NOT NULL,
	CREATED DATETIME,
	BILL_NO NVARCHAR(MAX),
	QUANTITY INT,
	PRICE INT,
	TOTAL INT,

	SUPPLIER_ID UNIQUEIDENTIFIER,
	ITEM_ID UNIQUEIDENTIFIER,

	CONSTRAINT PK_EXPORT_ITEM PRIMARY KEY (ID),
	CONSTRAINT FK_EXPORT_ITEM_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(ID),
	CONSTRAINT FK_EXPORT_ITEM_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID),
)


----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
SELECT *FROM ITEM
INSERT INTO ITEM VALUES ('', '', N'', N'', N'', N'', '', '', '')

SELECT *FROM EXPORT_ITEM
SET DATEFORMAT DMY INSERT INTO EXPORT_ITEM VALUES ('', '', N'', 1, 1, 1, '', '')
UPDATE EXPORT_ITEM SET CREATED = '', BILL_NO = N'', QUANTITY = 1, PRICE = 1, TOTAL = 1, SUPPLIER_ID = '', ITEM_ID = '' WHERE ID = ''
DELETE FROM EXPORT_ITEM WHERE ID = ''

SELECT *FROM GROUPS
INSERT INTO GROUPS VALUES('', N'')
UPDATE GROUPS SET NAME = N'' WHERE ID = ''
DELETE FROM GROUPS WHERE ID = ''

SELECT *FROM LOCATION_WAREHOUSE
INSERT INTO LOCATION_WAREHOUSE VALUES('', N'')
UPDATE LOCATION_WAREHOUSE SET NAME = N'' WHERE ID = ''
DELETE FROM LOCATION_WAREHOUSE WHERE ID = ''

SELECT *FROM MPR
SET DATEFORMAT DMY INSERT INTO MPR VALUES ('', '', '', N'', '')
UPDATE MPR SET CREATED = '', EXPECTED_DELIVERY = '', NOTE = N'', SUPPLIER_ID = '' WHERE ID = ''
DELETE FROM MPR WHERE ID = ''

SELECT *FROM MPR_DETAIL
INSERT INTO MPR_DETAIL VALUES ('', '', N'', N'', 1)

SELECT *FROM PAYMENT_METHOD
INSERT INTO PAYMENT_METHOD VALUES ('', N'')
UPDATE PAYMENT_METHOD SET NAME = N'' WHERE ID = ''
DELETE FROM PAYMENT_METHOD WHERE ID = ''

SELECT *FROM PO
SET DATEFORMAT DMY INSERT INTO PO VALUES ('', '', '', 1, '', '', '')
UPDATE PO SET CREATED = '', EXPECTED_DELIVERY = '', TOTAL = 1, SUPPLIER_ID = '', LOCATION_WAREHOUSE_ID = '', PAYMENT_METHOD_ID = '' WHERE ID = ''
DELETE FROM PO WHERE ID = ''

SELECT *FROM PO_DETAIL
INSERT INTO PO_DETAIL VALUES ('', '', N'', N'', 1, 1)

SELECT *FROM SUPPLIER
INSERT INTO SUPPLIER VALUES ('', N'', N'', N'', N'', N'', N'')
UPDATE SUPPLIER SET NAME_SUPPIER = N'', NAME_COMPANY_SUPPLIER = N'', ADDRESS = N'', PHONE = N'', EMAIL = N'', NOTE = N'' WHERE ID = ''
DELETE FROM SUPPLIER WHERE ID = ''

SELECT *FROM TYPES
INSERT INTO TYPES VALUES('', N'')
UPDATE TYPES SET NAME = N'' WHERE ID = ''
DELETE FROM TYPES WHERE ID = ''

----------------------------------------------------------------------------------------------------
-----------------------------PROCEDURE--------------------------------------------------------------
----------------------------------------------------------------------------------------------------

-------------------------------
-------------------------------
GO
CREATE PROC GET_ITEMS
AS
BEGIN
	SELECT ITEM.ID, CODE, ITEM.NAME, UNIT.NAME, PICTURE, GROUPS.NAME, SUPPLIER.NAME_COMPANY_SUPPLIER
	FROM ITEM, UNIT, GROUPS, SUPPLIER
	WHERE ITEM.UNIT_ID = UNIT.ID AND ITEM.GROUP_ID = GROUPS.ID AND ITEM.SUPPLIER_ID = SUPPLIER.ID
END
GO
EXEC GET_ITEMS

-------------------------------
-------------------------------
GO
CREATE PROC GET_CURRENT_CODE_SUPPLIER @KEY_CODE CHAR(3)
AS
BEGIN
	SELECT MAX(RIGHT(CODE, 4)) FROM SUPPLIER 
	WHERE CODE LIKE '%' + @KEY_CODE
END
GO



----------------------------------------------------------------------------------------------------
-------------------------------FUNCTION-------------------------------------------------------------
----------------------------------------------------------------------------------------------------